namespace Azzs.Ui.DesignSystem.Controls
{
    [default_interface]
    runtimeclass ReadOnlyPresentationSurface : Microsoft.UI.Xaml.Controls.UserControl
    {
        ReadOnlyPresentationSurface();
    }
}
